homeassistant: true
permit_join: true
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://mosquitto:1883
serial:
  port: /dev/ttyUSB0   # ajuste para seu adaptador
frontend:
  port: 8080
advanced:
  log_output:
    - console
